name: water_tracker_app_new
description: "A new Flutter project."
publish_to: 'none'  # Убирает публикацию на pub.dev

version:  1.0.0+1

environment:
  sdk:  ^3.7.0

dependencies:
  flutter:
    sdk:  flutter

  # iOS-style icons
  cupertino_icons:  ^1.0.8

  # Локальное хранение
  shared_preferences:  ^2.0.15

  # Firebase core
  firebase_core:  ^3.14.0

  # Аутентификация через Firebase
  firebase_auth:  ^5.6.0

  # Google Sign-In
  google_sign_in:  ^6.1.0

  # Хранилище в облаке (обновлено до последней, совместимой с Dart 3.7)
  cloud_firestore:  ^5.6.9

dev_dependencies:
  flutter_test:
    sdk:  flutter

  # Совместимая с Dart 3.7.0 версия lint-ов
  flutter_lints:  ^5.0.0

flutter:
  uses-material-design:  true